#!/bin/sh

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="$POSTGRES_DB" <<-EOSQL
	CREATE EXTENSION IF NOT EXISTS pg_stat_statements CASCADE;
	CREATE EXTENSION IF NOT EXISTS pg_stat_kcache CASCADE;
	CREATE EXTENSION IF NOT EXISTS postgis CASCADE;
	CREATE EXTENSION IF NOT EXISTS postgis_topology CASCADE;
EOSQL
