version: '3'

networks:
  overlay:
    driver: overlay

services:
  postgres:
    build: .
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    networks:
      - overlay
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - overlay
    ports:
      - 5433:80
